import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainTable from '../components/MainTable';

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Let's Find The House For You
        </h1>
        <br/>
        <MainTable {...data}/>
      </main>
    </div>
  )
}
export async function getStaticProps(context) {
  return {
    props: {
      data: {
        tableConfig: {
          columnNames: [
            "column 1",
            "column 2",
            "column 3",
            "column 4",
            "column 5",
            "column 6",
            "column 7",
            "column 8"
          ]
        },
        tableRows: [
        {
          col1: 'hello',
          col2: 'new',
          col3: 'world!',
          col4: 'we',
          col5: 'have',
          col6: 'new',
          col7: 'data'
        }, {
          col1: 'here',
          col2: 'is',
          col3: 'row 2!',
        }
      ]
    }
    }
  }
}
